-- AlterTable
ALTER TABLE "Otp" ADD COLUMN "channel" TEXT NOT NULL DEFAULT 'EMAIL';
ALTER TABLE "Otp" ADD COLUMN "attempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Otp" ADD COLUMN "invalidatedAt" DATETIME;
